#!/usr/bin/env node
/**
 * import.js — แปลง JSON เวรรายวัน (จาก Apps Script rbExportDayJson/rbSaveDayJson)
 *             → SQL สำหรับตาราง duty + assignment (idempotent ต่อวัน)
 *
 * ใช้:
 *   node db/import.js pas_export_2026-09-19.json | psql -d pas
 *   cat day.json | node db/import.js | psql "$DATABASE_URL"
 *
 * ออกแบบให้ไม่พึ่ง driver (พ่น SQL ออก stdout) → ทดสอบ/รันได้ทันทีด้วย psql
 * โปรดักชันจะสลับเป็น pg parameterized ก็ได้ โดยใช้ mapping เดียวกันนี้
 */
'use strict';
const fs = require('fs');

// ---------- helpers ----------
function esc(v) {
  if (v === null || v === undefined || v === '') return 'NULL';
  return "'" + String(v).replace(/'/g, "''") + "'";
}
function num(v) { const n = Number(v); return Number.isFinite(n) ? String(n) : 'NULL'; }
function intOrNull(v) { const n = parseInt(v, 10); return Number.isFinite(n) ? String(n) : 'NULL'; }
function boolLit(v) { return v ? 'TRUE' : 'FALSE'; }
function timeLit(v) {                                  // "7:45" / "07:45" / "0745" → TIME literal, ไม่งั้น NULL
  if (v === null || v === undefined) return 'NULL';
  const m = String(v).match(/(\d{1,2})[:.]?(\d{2})/);
  if (!m) return 'NULL';
  const h = +m[1], mi = +m[2]; if (h > 29 || mi > 59) return 'NULL';
  return "'" + String(h % 24).padStart(2, '0') + ':' + String(mi).padStart(2, '0') + ":00'";
}
const BUCKET = { working: 'WORKING', ot_off: 'OT_OFF', off: 'OFF', sick: 'SICK', vac: 'VACATION', vacation: 'VACATION', leave: 'LEAVE' };
function bucket(b) { return BUCKET[String(b || '').toLowerCase()] || 'OFF'; }
function otType(t) { const u = String(t || '').toUpperCase(); return (u === 'PRE' || u === 'POST') ? "'" + u + "'" : 'NULL'; }
function empCode(id) { const d = String(id || '').replace(/\D/g, ''); return /^\d{6,8}$/.test(d) ? d : null; }
function airlineOf(leg) { const m = String(leg || '').toUpperCase().match(/^([0-9A-Z]{2})/); return m ? m[1] : null; }
function leg(flight) { return String(flight || '').split('/')[0].trim(); }
function q(s) { process.stdout.write(s + '\n'); }

// ---------- read JSON (file arg or stdin) ----------
function readInput() {
  const arg = process.argv[2];
  if (arg && arg !== '-') return fs.readFileSync(arg, 'utf8');
  return fs.readFileSync(0, 'utf8');
}

function main() {
  const data = JSON.parse(readInput());
  const date = data.date;
  if (!date) { console.error('no "date" in JSON'); process.exit(1); }
  const D = esc(date);

  q('-- generated by db/import.js for ' + date);
  q('BEGIN;');
  // team stubs (ให้ FK ของ employee/duty ผ่าน — เติมรายละเอียดทีมทีหลังได้)
  const teamSet = {};
  Object.keys(data.teams || {}).forEach(function (team) {
    if (team) teamSet[team] = 1;
    (data.teams[team] || []).forEach(function (r) { if (r.team) teamSet[r.team] = 1; if (r.supportTeam) teamSet[r.supportTeam] = 1; });
  });
  Object.keys(teamSet).forEach(function (t) { q('INSERT INTO team(code) VALUES(' + esc(t) + ') ON CONFLICT (code) DO NOTHING;'); });
  // idempotent: ล้างของวันนั้นก่อน (assignment ผูก duty ผ่าน FK ON DELETE CASCADE)
  q('DELETE FROM assignment WHERE duty_id IN (SELECT id FROM duty WHERE work_date = ' + D + ');');
  q('DELETE FROM duty WHERE work_date = ' + D + ';');

  let nDuty = 0, nAsg = 0;
  Object.keys(data.teams || {}).forEach(function (team) {
    (data.teams[team] || []).forEach(function (r) {
      const code = empCode(r.id);
      // upsert stub employee (เติมรายละเอียดเต็มทีหลังจาก master importer) เพื่อให้ FK ผ่าน
      if (code) {
        const src = r.bkk ? 'BKK' : 'HKT';
        q('INSERT INTO employee(emp_code,name_th,team_code,source) VALUES(' +
          esc(code) + ',' + esc(r.name) + ',' + esc(r.team || team) + ',' + esc(src) + ') ON CONFLICT (emp_code) DO NOTHING;');
      }
      const shiftStart = (r.shiftStart == null) ? null : r.shiftStart;
      const shiftEnd = (shiftStart != null && r.shiftHrs) ? Math.round(shiftStart + r.shiftHrs * 60) : null;
      const otSpans = r.otSpans ? esc(JSON.stringify(r.otSpans)) + '::jsonb' : 'NULL';
      q('WITH d AS (INSERT INTO duty(work_date,emp_code,emp_name,team_code,bucket,shift_code,shift_start,shift_end,shift_hours,re_sked,ot_hours,ot_type,ot_spans,is_support,support_from,is_bkk,is_training,remark,source_file) VALUES(' +
        [D, code ? esc(code) : 'NULL', esc(r.name), esc(r.team || team), "'" + bucket(r.bucket) + "'",
         esc(r.shift), intOrNull(shiftStart), intOrNull(shiftEnd), num(r.shiftHrs || 0), esc(r.reTime),
         num(r.ot || 0), otType(r.otType), otSpans, boolLit(r.support), esc(r.supportTeam),
         boolLit(r.bkk), boolLit(r.training), esc(r.remark), esc(data.sourceFile)].join(',') +
        ') RETURNING id)');
      nDuty++;
      const asg = r.assignments || [];
      if (!asg.length) { q('SELECT id FROM d;'); return; }   // ปิด CTE ให้ statement สมบูรณ์เมื่อไม่มี assignment
      const rows = asg.map(function (a) {
        const lg = leg(a.flight);
        return '(' + [
          esc(a.flight), esc(lg), esc(airlineOf(lg)), esc(a.task),
          boolLit(a.isFlight), boolLit(a.activity), boolLit(a.supportOut), esc(a.supportTeam),
          timeLit(a.STA), timeLit(a.STD), timeLit(a.OP), timeLit(a.CL), esc(a.flight)
        ].join(',') + ')';
      });
      q('INSERT INTO assignment(duty_id,flight_code,flight_leg,airline_iata,task,is_flight,is_activity,is_support_out,support_to,sta,std,counter_open,counter_close,raw) ' +
        'SELECT d.id,x.flight_code,x.flight_leg,x.airline_iata,x.task,x.is_flight::boolean,x.is_activity::boolean,x.is_support_out::boolean,x.support_to,' +
        'x.sta::time,x.std::time,x.counter_open::time,x.counter_close::time,x.raw ' +
        'FROM d, (VALUES ' + rows.join(',') + ') AS x(flight_code,flight_leg,airline_iata,task,is_flight,is_activity,is_support_out,support_to,sta,std,counter_open,counter_close,raw);');
      nAsg += asg.length;
    });
  });

  q('COMMIT;');
  console.error('duty=' + nDuty + ' assignment=' + nAsg + ' (date ' + date + ')');
}
main();
